stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: extras/docker/Dockerfile
      buildContext: .
      tag: wilma_img:7.7
      pushRemote: true
      registry: 192.168.100.176:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./ingress.yaml
timeout: 60
notification: {}
