apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  #namespace: test
  namespace: default
  name: wilma1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: wilma1
    spec:
      containers:
      - env:
        - name: PEP_PASSWORD
          value: pep_proxy_721d70f7-5bae-4559-b6d7-37c677f250e1
        - name: PEP_PROXY_APP_HOST
          value: iot-agent
        - name: PEP_PROXY_APP_ID
          value: 1f43a0f5-3efd-4276-9834-f50517a4c548
        - name: PEP_PROXY_APP_PORT
          value: "30190"
        - name: PEP_PROXY_IDM_HOST
          value: 172.30.70.53
        - name: PEP_PROXY_IDM_PORT
          value: "30999"
        - name: PEP_PROXY_PORT
          value: "5556"
        - name: PEP_PROXY_USERNAME
          value: pep_proxy_4d353464-bc27-412c-b7ea-b9e4035620f7
        #image: 172.30.76.49:5000/wilma 
        image: 172.30.76.49:5000/wilma_image:7.7
        name: wilma1
        ports:
        - containerPort: 5556
