apiVersion: v1
kind: Service
metadata:
  #namespace: fiware
  namespace: default
  labels:
    name: wilma1
  name: wilma1
spec:
  type: NodePort
  ports:
  - name: "5556"
    port: 5556
    nodePort: 30193
  selector:
    name: wilma1

